name: check-r-package

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  check-package:
    name: Run R CMD CHECK for a package 
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2

